In [16]:
import pandas as pd
import numpy as np
df = pd.read_csv("Football_dataset.csv")
df

,Team,Tournament,Goals Scored,Shots pg,Yellow Cards,Red Cards,Shooting Accuracy,AerialsWon,Rating,Discipline,Own Fouls,Opponent Fouls
0,Manchester City,Premier League,83,15.8,46,2,89.4,12.8,7.01,48,1,1
1,Bayern Munich,Bundesliga,99,17.1,44,3,85.5,12.9,6.95,47,2,2
2,Paris Saint-Germain,Ligue 1,86,15.0,73,7,89.5,9.5,6.88,80,3,3
3,Barcelona,LaLiga,85,15.3,68,2,89.7,10.6,6.87,70,4,5
4,Real Madrid,LaLiga,67,14.4,57,2,87.7,11.8,6.86,59,5,6
5,Manchester United,Premier League,73,13.8,64,1,84.8,14.5,6.85,65,6,7
6,Juventus,Serie A,77,15.7,76,6,88.3,11.4,6.85,82,7,1
7,Aston Villa,Premier League,55,13.7,63,4,78.6,19.4,6.84,67,8,2
8,Borussia Dortmund,Bundesliga,75,14.6,43,1,85.5,12.8,6.84,44,1,3
9,Atletico Madrid,LaLiga,67,12.1,100,0,83.1,14.4,6.84,100,2,5
10,Atalanta,Serie A,90,16.3,66,3,83.5,16.8,6.84,69,3,6
11,Chelsea,Premier League,58,14.6,49,3,87.0,15.2,6.83,52,4,7
12,Liverpool,Premier League,68,16.0,40,0,85.7,14.3,6.82,40,5,1
13,AC Milan,Serie A,74,14.7,80,4,84.0,15.2,6.82,84,6,2
14,Lille,Ligue 1,64,12.8,67,2,83.5,15.8,6.82,69,7,3
15,Tottenham,Premier League,68,11.7,53,2,81.8,16.4,6.81,55,8,5
16,Napoli,Serie A,86,17.0,71,3,87.0,11.1,6.81,74,1,6
17,Leicester,Premier League,68,12.8,61,0,82.1,16.2,6.80,61,2,7
18,Wolfsburg,Bundesliga,61,14.1,56,3,78.0,16.9,6.80,59,3,1
19,Inter,Serie A,89,14.5,59,2,87.0,11.8,6.80,61,4,2
20,Lyon,Ligue 1,81,16.1,60,10,84.7,14.3,6.80,70,5,3
21,RB Leipzig,Bundesliga,60,16.0,57,0,83.2,18.6,6.78,57,6,5
22,Leeds,Premier League,62,13.7,61,1,80.8,14.5,6.77,62,7,6
23,West Ham,Premier League,62,12.3,48,3,77.8,19.9,6.77,51,8,7
24,Everton,Premier League,47,10.5,59,2,81.4,17.7,6.73,61,1,1
25,Bayer Leverkusen,Bundesliga,53,13.0,58,0,84.4,13.1,6.73,58,2,2
26,Eintracht Frankfurt,Bundesliga,69,13.2,80,1,79.6,17.9,6.73,81,3,3
27,Monaco,Ligue 1,76,12.8,74,7,82.7,16.5,6.73,81,4,5
28,Roma,Serie A,68,14.3,84,3,84.5,12.1,6.71,87,5,6

In [17]:
df['Team'].value_counts()

Team
Manchester City        1
Tottenham              1
Monaco                 1
Eintracht Frankfurt    1
Bayer Leverkusen       1
Everton                1
West Ham               1
Leeds                  1
RB Leipzig             1
Lyon                   1
Inter                  1
Wolfsburg              1
Leicester              1
Napoli                 1
Lille                  1
Bayern Munich          1
AC Milan               1
Liverpool              1
Chelsea                1
Atalanta               1
Atletico Madrid        1
Borussia Dortmund      1
Aston Villa            1
Juventus               1
Manchester United      1
Real Madrid            1
Barcelona              1
Paris Saint-Germain    1
Roma                   1
Name: count, dtype: int64

In [18]:
df['Team'].nunique()

29

In [19]:
df.isnull().sum()

Team                 0
Tournament           0
Goals Scored         0
Shots pg             0
Yellow Cards         0
Red Cards            0
Shooting Accuracy    0
AerialsWon           0
Rating               0
Discipline           0
Own Fouls            0
Opponent Fouls       0
dtype: int64

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Team               29 non-null     object
 1   Tournament         29 non-null     object
 2   Goals Scored       29 non-null     int64
 3   Shots pg           29 non-null     float64
 4   Yellow Cards       29 non-null     int64
 5   Red Cards          29 non-null     int64
 6   Shooting Accuracy  29 non-null     float64
 7   AerialsWon         29 non-null     float64
 8   Rating             29 non-null     float64
 9   Discipline         29 non-null     int64
 10  Own Fouls          29 non-null     int64
 11  Opponent Fouls     29 non-null     int64
dtypes: float64(4), int64(6), object(2)
memory usage: 2.8+ KB

In [21]:
top_team = df.groupby('Team')['Discipline'].sum().nlargest(2)
top_team

Team
Atletico Madrid    100
Roma                87
Name: Discipline, dtype: int64

In [22]:
low_team = df.groupby('Team')['Discipline'].sum().nsmallest(2)
low_team

Team
Liverpool            40
Borussia Dortmund    44
Name: Discipline, dtype: int64

In [23]:
avg_ylw = df.groupby('Team')['Yellow Cards'].mean()
avg_ylw

Team
AC Milan                80.0
Aston Villa             63.0
Atalanta                66.0
Atletico Madrid        100.0
Barcelona               68.0
Bayer Leverkusen        58.0
Bayern Munich           44.0
Borussia Dortmund       43.0
Chelsea                 49.0
Eintracht Frankfurt     80.0
Everton                 59.0
Inter                   59.0
Juventus                76.0
Leeds                   61.0
Leicester               61.0
Lille                   67.0
Liverpool               40.0
Lyon                    60.0
Manchester City         46.0
Manchester United       64.0
Monaco                  74.0
Napoli                  71.0
Paris Saint-Germain     73.0
RB Leipzig              57.0
Real Madrid             57.0
Roma                    84.0
Tottenham               53.0
West Ham                48.0
Wolfsburg               56.0
Name: Yellow Cards, dtype: float64

In [24]:
df['Yellow Cards'].mean()

62.6551724137931

In [25]:
avg_red = df.groupby('Team')['Red Cards'].mean()
avg_red

Team
AC Milan                4.0
Aston Villa             4.0
Atalanta                3.0
Atletico Madrid         0.0
Barcelona               2.0
Bayer Leverkusen        0.0
Bayern Munich           3.0
Borussia Dortmund       1.0
Chelsea                 3.0
Eintracht Frankfurt     1.0
Everton                 2.0
Inter                   2.0
Juventus                6.0
Leeds                   1.0
Leicester               0.0
Lille                   2.0
Liverpool               0.0
Lyon                   10.0
Manchester City         2.0
Manchester United       1.0
Monaco                  7.0
Napoli                  3.0
Paris Saint-Germain     7.0
RB Leipzig              0.0
Real Madrid             2.0
Roma                    3.0
Tottenham               2.0
West Ham                3.0
Wolfsburg               3.0
Name: Red Cards, dtype: float64

In [26]:
high_scoring_teams = df[df['Goals Scored'] > 5]

unique_teams_count = high_scoring_teams['Team'].nunique()

print(unique_teams_count)


team_goals_subset = high_scoring_teams[['Team', 'Goals Scored']]

print(team_goals_subset.head(2))

29
              Team  Goals Scored
0  Manchester City            83
1    Bayern Munich            99

In [27]:
sht_acry = df.loc[df['Shooting Accuracy'].idxmax()]
sht_acry[['Team', 'Shooting Accuracy']]

Team                 Barcelona
Shooting Accuracy         89.7
Name: 3, dtype: object

In [28]:
team_more_foul = df[df['Own Fouls']>df['Opponent Fouls']]
num_teams_foul = team_more_foul['Team'].unique()
# print(team_more_foul)
print(num_teams_foul)
print("\n")

print(team_more_foul[['Team','Own Fouls', 'Opponent Fouls']])

['Juventus' 'Aston Villa' 'Liverpool' 'AC Milan' 'Lille' 'Tottenham'
 'Wolfsburg' 'Inter' 'Lyon' 'RB Leipzig' 'Leeds' 'West Ham']


           Team  Own Fouls  Opponent Fouls
6      Juventus          7               1
7   Aston Villa          8               2
12    Liverpool          5               1
13     AC Milan          6               2
14        Lille          7               3
15    Tottenham          8               5
18    Wolfsburg          3               1
19        Inter          4               2
20         Lyon          5               3
21   RB Leipzig          6               5
22        Leeds          7               6
23     West Ham          8               7